server:
  port: 8763
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      ## mq 连接信息地址
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: zhangdeenpd@163.com
    password: MSBPEGUYESZNNLVS 
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
